### ISSUE TITLE
README does not match current version from NuGet

### ISSUE THREAD

**Issue by tidyui** [sergeyt/Owin.Routing#10]
The "getting started" docs in the README doesn't seem to match the current version. I had to replace the following code:

    app.Route("docs/{collection}")
        .Get(async (ctx, data) =>
        {
            var name = Convert.ToString(data.Values["collection"]);
            await ctx.Response.WriteAsync(name);
        });

with:

    app.Route("docs/{collection}")
        .Get(async (ctx) =>
        {
            var name = var name = ctx.GetRouteValue<string>("name"); 
            await ctx.Response.WriteAsync(name);
        });

**Comment by sergeyt** [comment]
@tidyui thanks for info, fixed!
